"""tests/test_harness_artifacts.py

Post-run assertion suite for the harness integration test (TASK-008 through TASK-011).

USAGE
-----
This suite is split into two tiers:

  Tier 1 — Always runs (stateless, no runner required):
      pytest tests/test_harness_artifacts.py

  Tier 2 — Requires a full harness run first:
      python agent/runner.py --no-prewarm
      HARNESS_RUN=1 pytest tests/test_harness_artifacts.py

KNOWN ISSUES
------------
audit.json / harness_result.json:
    These files are GENERATED AT RUNTIME by agent/runner.py executing TASK-011
    (the audit ticket). They do NOT exist on a clean checkout or after 'git clean'.
    They are deliberately NOT committed to the repo (they are runtime state).

    Resolution: run 'python agent/runner.py --no-prewarm' to completion before
    running this suite. Set HARNESS_RUN=1 env var to promote the skipif to an
    assertion (CI enforcement mode).

    Gate protocol: the default 'pytest tests/ -v' run SKIPS these two tests.
    Only CI or a manual harness run with HARNESS_RUN=1 enforces them.

All other tests in this file are read-only and safe to run at any time.
"""

import json
import os
import pytest

# Set HARNESS_RUN=1 to enforce runtime-generated artifact tests (e.g. in CI
# after agent/runner.py --no-prewarm has been executed as a pre-test step).
_HARNESS_RUN = os.environ.get("HARNESS_RUN", "0") == "1"

ARTIFACTS_STATIC = [
    "output/word_freq.py",
    "output/report.md",
]

# These two are generated by runner.py TASK-011 — not present on clean checkout.
ARTIFACTS_RUNTIME = [
    "output/audit.json",
    "output/harness_result.json",
]

ARTIFACTS_ALL = ARTIFACTS_STATIC + ARTIFACTS_RUNTIME

ATTEMPT_LOGS = [
    "logs/TASK-008-attempts.jsonl",
    "logs/TASK-009-attempts.jsonl",
    "logs/TASK-010-attempts.jsonl",
    "logs/TASK-011-attempts.jsonl",
]


# --- Tier 1: static artifacts (always enforced) ---

@pytest.mark.parametrize("path", ARTIFACTS_STATIC)
def test_static_artifact_exists(path):
    """Static artifacts committed to repo — must always exist."""
    assert os.path.exists(path), f"Missing static artifact: {path}"


@pytest.mark.parametrize("path", ARTIFACTS_ALL)
def test_artifact_nonempty(path):
    if not os.path.exists(path):
        pytest.skip(f"artifact missing (may need harness run): {path}")
    assert os.path.getsize(path) > 0, f"Empty artifact: {path}"


def test_word_freq_contains_the():
    path = "output/word_freq.py"
    if not os.path.exists(path):
        pytest.skip("word_freq.py missing")
    content = open(path).read()
    assert "the" in content.lower(), "word_freq.py must reference 'the'"


def test_report_contains_top_words_section():
    path = "output/report.md"
    if not os.path.exists(path):
        pytest.skip("report.md missing")
    content = open(path).read()
    assert "## Top Words" in content, "report.md must contain '## Top Words' section"


# --- Tier 2: runtime artifacts (require HARNESS_RUN=1 or skipped) ---

@pytest.mark.parametrize("path", ARTIFACTS_RUNTIME)
def test_runtime_artifact_exists(path):
    """KNOWN ISSUE: these files are generated by agent/runner.py --no-prewarm.
    They do not exist on a clean checkout. Set HARNESS_RUN=1 to enforce.
    Default behaviour: skip with explanation.
    """
    if not _HARNESS_RUN and not os.path.exists(path):
        pytest.skip(
            f"Runtime artifact not present: {path}. "
            "Run 'python agent/runner.py --no-prewarm' then set HARNESS_RUN=1 to enforce."
        )
    assert os.path.exists(path), (
        f"Missing runtime artifact: {path}. "
        "Ensure agent/runner.py completed TASK-011 successfully."
    )


def test_audit_json_schema():
    path = "output/audit.json"
    if not os.path.exists(path):
        pytest.skip("audit.json missing — run agent/runner.py --no-prewarm first")
    with open(path) as f:
        data = json.load(f)
    assert data.get("test_run") == "harness-integration-v1"
    assert data.get("report_contains_top_words") is True
    assert isinstance(data.get("report_char_count"), int)
    assert isinstance(data.get("artifacts_produced"), list)
    assert "ts" in data


def test_harness_result_passed():
    path = "output/harness_result.json"
    if not os.path.exists(path):
        pytest.skip("harness_result.json missing — run agent/runner.py --no-prewarm first")
    with open(path) as f:
        data = json.load(f)
    assert data.get("passed") is True, (
        f"Harness result not passed. failed_checks: {data.get('failed_checks')}"
    )


# --- Attempt logs (Tier 1 — logs committed to repo) ---

@pytest.mark.parametrize("path", ATTEMPT_LOGS)
def test_attempt_log_exists(path):
    assert os.path.exists(path), f"Missing attempt log: {path}"


@pytest.mark.parametrize("path", ATTEMPT_LOGS)
def test_attempt_log_valid_jsonl(path):
    if not os.path.exists(path):
        pytest.skip(f"log missing: {path}")
    lines = open(path).read().strip().splitlines()
    assert len(lines) >= 1, f"Empty attempt log: {path}"
    for i, line in enumerate(lines):
        record = json.loads(line)
        assert "outcome" in record, f"{path} line {i+1} missing 'outcome' field"
        assert "ticket_id" in record, f"{path} line {i+1} missing 'ticket_id' field"
        assert "tokens" in record, f"{path} line {i+1} missing 'tokens' field"
        assert record["outcome"] in ("pass", "fail", "error"), (
            f"{path} line {i+1} invalid outcome: {record['outcome']}"
        )


@pytest.mark.parametrize("path", ATTEMPT_LOGS)
def test_attempt_log_has_pass_outcome(path):
    """At least one attempt per ticket must have outcome=pass (ticket closed)."""
    if not os.path.exists(path):
        pytest.skip(f"log missing: {path}")
    lines = open(path).read().strip().splitlines()
    outcomes = [json.loads(l)["outcome"] for l in lines]
    assert "pass" in outcomes, (
        f"{path}: no passing attempt found. outcomes={outcomes}"
    )
